# Generated by Django 5.2.2 on 2025-07-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("duration_days", models.PositiveIntegerField()),
                ("departure_date", models.DateField()),
                ("group_size_current", models.PositiveIntegerField()),
                ("group_size_max", models.PositiveIntegerField()),
                ("price_gbp", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
