# Generated by Django 5.2.2 on 2025-07-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initials", models.CharField(max_length=10)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("bookings_count", models.PositiveIntegerField(default=0)),
                ("last_interaction_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
