# Generated by Django 5.2.4 on 2025-08-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="max_group_size",
            field=models.PositiveIntegerField(default=15),
        ),
    ]
