# Generated by Django 5.2.4 on 2025-08-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_tour_max_group_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="tour",
            name="excluded_services",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tour",
            name="highlights",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="tour",
            name="included_services",
            field=models.TextField(default=""),
        ),
    ]
