# Generated by Django 5.2.4 on 2025-08-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_tour_description_alter_tour_excluded_services_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentupload",
            name="processing_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about processing", null=True
            ),
        ),
    ]
