# Generated by Django 5.2.4 on 2025-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_documentupload_processing_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourdeparture",
            name="breakeven_passengers",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of passengers needed to break even",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tourdeparture",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Commission rate as percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tourdeparture",
            name="current_price_per_person",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="tourdeparture",
            name="discounted_price_per_person",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tourdeparture",
            name="fixed_costs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed costs for this departure (guides, permits, etc.)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tourdeparture",
            name="marketing_costs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Marketing and promotion costs",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tourdeparture",
            name="profit_at_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Profit if departure sells out",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tourdeparture",
            name="roi_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Return on Investment percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tourdeparture",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tourdeparture",
            name="variable_costs_per_person",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Variable costs per person (accommodation, meals, transport)",
                max_digits=10,
            ),
        ),
    ]
