# Generated by Django 5.2.2 on 2025-07-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customer_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                ("duration_days", models.PositiveIntegerField()),
                ("price_gbp", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "highlights",
                    models.TextField(help_text="Key highlights of the tour"),
                ),
                (
                    "included_services",
                    models.TextField(help_text="What's included in the tour"),
                ),
                (
                    "excluded_services",
                    models.TextField(
                        blank=True, help_text="What's not included in the tour"
                    ),
                ),
                ("max_group_size", models.PositiveIntegerField()),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                            ("expert", "Expert"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="URL to tour image", null=True
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
    ]
