# Generated by Django 5.2.4 on 2025-09-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tourdeparture_breakeven_passengers_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_customer_tour_operator_full_name ON core_customer (tour_operator_id, full_name);",
            reverse_sql="DROP INDEX IF EXISTS idx_customer_tour_operator_full_name;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_tourdeparture_tour_operator ON core_tourdeparture (tour_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_tourdeparture_tour_operator;"
        ),
    ]
