# Generated by Django 5.2.2 on 2025-07-29 05:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tour"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Tour image",
                null=True,
                upload_to=core.models.tour_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (alternative to file upload)",
                null=True,
            ),
        ),
    ]
