# Generated by Django 5.2.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250926_1215'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_unique_email_per_operator ON core_customer (tour_operator_id, LOWER(email));",
            reverse_sql="DROP INDEX IF EXISTS idx_customer_unique_email_per_operator;"
        ),
    ]
