# Generated by Django 5.2.4 on 2025-07-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_tour_image_alter_tour_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cancellation_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage of bookings cancelled",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_segment",
            field=models.CharField(
                choices=[
                    ("premium", "Premium"),
                    ("regular", "Regular"),
                    ("budget", "Budget"),
                    ("new", "New Customer"),
                ],
                default="new",
                help_text="Customer segment classification",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_spent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount spent by customer",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="cost_per_person",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost per person for this tour",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="operational_costs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed operational costs for this tour",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="profit_margin_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Expected profit margin percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="seasonal_demand",
            field=models.CharField(
                choices=[
                    ("high", "High Season"),
                    ("medium", "Medium Season"),
                    ("low", "Low Season"),
                    ("year_round", "Year Round"),
                ],
                default="medium",
                help_text="Seasonal demand pattern",
                max_length=20,
            ),
        ),
    ]
