# Generated by Django 5.2.4 on 2025-07-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_customer_cancellation_rate_customer_customer_segment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departure",
            name="price_gbp",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="price_gbp",
        ),
        migrations.AddField(
            model_name="departure",
            name="price_per_person",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price per person (PPP)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="departure",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("per_person", "Price Per Person (PPP)"),
                    ("total_tour", "Total Tour Price"),
                ],
                default="per_person",
                help_text="How is this departure priced?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="departure",
            name="total_tour_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total price for the entire tour",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="price_per_person",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price per person (PPP)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("per_person", "Price Per Person (PPP)"),
                    ("total_tour", "Total Tour Price"),
                ],
                default="per_person",
                help_text="How is this tour priced?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="total_tour_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total price for the entire tour",
                max_digits=10,
            ),
        ),
    ]
