# Generated by Django 5.2.4 on 2025-07-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_departure_price_gbp_remove_tour_price_gbp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departure",
            name="total_tour_price",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="total_tour_price",
        ),
        migrations.AddField(
            model_name="departure",
            name="price_per_group",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total price for the entire group",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="price_per_group",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total price for the entire group",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="departure",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("per_person", "Price Per Person (PPP)"),
                    ("per_group", "Price Per Group"),
                ],
                default="per_person",
                help_text="How is this departure priced?",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("per_person", "Price Per Person (PPP)"),
                    ("per_group", "Price Per Group"),
                ],
                default="per_person",
                help_text="How is this tour priced?",
                max_length=20,
            ),
        ),
    ]
