# Generated by Django 5.2.2 on 2025-07-29 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_departure_total_tour_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourDeparture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateField()),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="core.tour",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Departure",
        ),
    ]
